#########################################
# ServerHandler configuration
# [\u534F\u8BAE\u540D\u79F0] = \u534F\u8BAE\u5904\u7406\u7406\u5668\u7C7B\u8DEF\u5F84
#########################################
#TCP\u534F\u8BAE\u5904\u7406\u5668
tcp = xyz.jasenon.lab.server.protocol.tcp.TcpProtocolHandler
#ws\u534F\u8BAE\u5904\u7406\u5668
ws = xyz.jasenon.lab.server.protocol.ws.WsProtocolHandler

