#########################################
# CommandHandler configuration
#########################################
#3 = xyz.jasenon.lab.server.command.handler.AuthReqHandler
#14 = xyz.jasenon.lab.server.command.handler.CloseReqHandler
#1 = xyz.jasenon.lab.server.command.handler.HandshakeReqHandler,xyz.jasenon.lab.server.processor.handshake.TcpHandshakeProcessor,xyz.jasenon.shimi.im.command.processor.handshake.WsHandshakeProcessorWithSaToken
#13 = xyz.jasenon.lab.server.command.handler.HeartbeatReqHandler
#7 = xyz.jasenon.lab.server.command.handler.JoinGroupReqHandler
#11 = xyz.jasenon.lab.server.command.handler.ChatReqHandler,xyz.jasenon.shimi.im.command.processor.chat.ChatProcessor
#17 = xyz.jasenon.lab.server.command.handler.ClassTimeTableReqHandler
#19 = xyz.jasenon.lab.server.command.handler.MessageReqHandler
#5 = xyz.jasenon.lab.server.command.handler.LoginReqHandler,xyz.jasenon.shimi.im.command.processor.login.LoginProcessor
#21 = xyz.jasenon.shimi.im.command.handler.FriendReqHandler,xyz.jasenon.shimi.im.command.processor.friend.FriendProcessor
#23 = xyz.jasenon.shimi.im.command.handler.FriendHandleReqHandler,xyz.jasenon.shimi.im.command.processor.friend.FriendProcessor
#25 = xyz.jasenon.shimi.im.command.handler.FriendListReqHandler,xyz.jasenon.shimi.im.command.processor.friend.FriendProcessor
#27 = xyz.jasenon.shimi.im.command.handler.FriendReqListReqHandler,xyz.jasenon.shimi.im.command.processor.friend.FriendProcessor
