server:
  port: 8083

# t-io ws 服务器配置
t-io:
  server:
    name: smart-board-server
    host: 0.0.0.0
    port: 9000
    heartbeat: 60000

# 日志配置
logging:
  level:
    xyz.jasenon.lab.class_time_table: DEBUG
    xyz.jasenon.lab.tioprotocol: DEBUG
