##J-IM????
#ip
jim.bind.ip = 127.0.0.1
#??
jim.port = 8888
#??????
jim.heartbeat.timeout = 0
#?????????(on:??,off:???)
jim.store = off
#??????(on:??,off:???)
jim.cluster = off
#????SSL(on:??,off:???)
jim.ssl = off
#JKS????
jim.key.store.path = classpath:ssl/keystore.jks
#JKS????
jim.key.store.pwd = 214323428310224

##http?? ??
#html/css/js????????classpath:???????
jim.http.page = classpath:page
#http mvc?????
jim.http.scan.packages =
#http??????
jim.http.max.live.time = 0

##ws????


##Redis????
#?????????,????????
jim.redis.retrynum = 100
#????????????????8?
jim.redis.maxactive = -1
#????pool?????????idle(???)?jedis????????8?
jim.redis.maxidle = 20
#?????????????????????-1????????
jim.redis.maxwait = 5000
jim.redis.timeout = 2000
#redis????ip
jim.redis.host = 127.0.0.1
#redis???
jim.redis.port = 6379
#redis??
jim.redis.auth = 
