-- H2 兼容的测试数据库 Schema

-- 实验室表
CREATE TABLE IF NOT EXISTS laboratory (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    laboratory_id VARCHAR(64) NOT NULL,
    laboratory_name VARCHAR(128) NOT NULL,
    belong_to_depts VARCHAR(512),
    belong_to_building VARCHAR(128),
    security_level VARCHAR(32),
    class_capacity INT,
    area VARCHAR(32),
    intro TEXT,
    create_time TIMESTAMP,
    update_time TIMESTAMP
);

-- 学期表
CREATE TABLE IF NOT EXISTS semester (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(128) NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    create_time TIMESTAMP NULL,
    update_time TIMESTAMP NULL,
    deleted BOOLEAN DEFAULT FALSE
);

-- 课程表
CREATE TABLE IF NOT EXISTS course (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_name VARCHAR(128) NOT NULL,
    volumn INT NOT NULL,
    grade VARCHAR(16) NULL,
    create_time TIMESTAMP NULL,
    update_time TIMESTAMP NULL,
    deleted BOOLEAN DEFAULT FALSE
);

-- 课表表
CREATE TABLE IF NOT EXISTS course_schedule (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    semester_id BIGINT NOT NULL,
    laboratory_id BIGINT NOT NULL,
    week_type TINYINT NOT NULL,
    start_week INT NOT NULL,
    end_week INT NOT NULL,
    start_time TIME NOT NULL,
    end_time TIME NOT NULL,
    weekdays VARCHAR(512) NOT NULL,
    course_id BIGINT NOT NULL,
    teacher_id BIGINT NOT NULL,
    dept_id BIGINT NULL,
    major_class VARCHAR(128) NULL,
    start_section INT NULL,
    end_section INT NULL,
    mark TEXT NULL,
    create_time TIMESTAMP NULL,
    update_time TIMESTAMP NULL,
    deleted BOOLEAN DEFAULT FALSE
);

-- 定时任务表
CREATE TABLE IF NOT EXISTS schedule_task (
    id VARCHAR(64) PRIMARY KEY,
    task_name VARCHAR(128) NOT NULL,
    cron VARCHAR(64) NOT NULL,
    enable VARCHAR(8) NOT NULL,
    start_date DATE,
    end_date DATE,
    laboratory_id BIGINT NULL
);

-- 时间规则表
CREATE TABLE IF NOT EXISTS time_rule (
    id VARCHAR(64) PRIMARY KEY,
    schedule_task_id VARCHAR(64) NOT NULL UNIQUE,
    semester_id BIGINT NULL,
    weekdays VARCHAR(512) NOT NULL,
    start_week INT NOT NULL,
    end_week INT NOT NULL,
    week_type VARCHAR(16) NOT NULL,
    start_time TIME NOT NULL,
    end_time TIME NOT NULL
);

-- 条件组表
CREATE TABLE IF NOT EXISTS condition_group (
    id VARCHAR(64) PRIMARY KEY,
    type VARCHAR(16) NOT NULL,
    schedule_task_id VARCHAR(64) NOT NULL
);

-- 条件表
CREATE TABLE IF NOT EXISTS "condition" (
    id VARCHAR(64) PRIMARY KEY,
    expr VARCHAR(512) NOT NULL,
    "desc" VARCHAR(255),
    condition_group_id VARCHAR(64) NOT NULL,
    schedule_task_id VARCHAR(64) NOT NULL
);

-- 动作组表
CREATE TABLE IF NOT EXISTS action_group (
    id VARCHAR(64) PRIMARY KEY,
    schedule_task_id VARCHAR(64) NOT NULL,
    condition_group_id VARCHAR(64) NOT NULL
);

-- 动作表
CREATE TABLE IF NOT EXISTS "action" (
    id VARCHAR(64) PRIMARY KEY,
    device_type VARCHAR(32) NOT NULL,
    device_id BIGINT NOT NULL,
    command_line VARCHAR(64) NOT NULL,
    args VARCHAR(2048) NOT NULL,
    action_group_id VARCHAR(64) NOT NULL,
    schedule_task_id VARCHAR(64) NOT NULL
);

-- 数据源表
CREATE TABLE IF NOT EXISTS "data" (
    id VARCHAR(64) PRIMARY KEY,
    schedule_task_id VARCHAR(64) NOT NULL,
    device_id BIGINT NOT NULL,
    device_type VARCHAR(32) NOT NULL
);

-- 报警表
CREATE TABLE IF NOT EXISTS alarm (
    id VARCHAR(64) PRIMARY KEY,
    schedule_task_id VARCHAR(64) NOT NULL,
    user_id BIGINT NOT NULL,
    type VARCHAR(16) NOT NULL
);
